version: '3.1'
services:
  nexus:
    restart: always
    image: sonatype/nexus3:3.11.0
    container_name: nexus
    ports:
      - 8081:8081
    volumes:
      - /usr/local/docker/nexus/data:/nexus-data
      - /usr/local/docker/nexus/opt:/opt/sonatype/nexus/etc/jett